version: '3'

services:
  mongo:
    container_name: mongo
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
    ports:
      - "27017:27017"
    volumes:
      - /db:/data/db
    networks:
      - mongo-compose-network

networks:
  mongo-compose-network:
    driver: bridge
